MVC5i18n/Models/LanguageItemModel.cs
using System;
using System.Web.Mvc;

namespace MVC5i18n.Models
{
    /// <summary>
    /// Classe définissant le modèle d'un element du menu
    /// </summary>
    public class LanguageItemModel 
    {
        public string Name { get; set; }
        /// <summary>
        /// Gets the action URL.
        /// </summary>
        /// <value>The action URL.</value>
        public string ActionUrl { get; set; }

        /// <summary>
        /// Gets the picto URL.
        /// </summary>
        /// <value>The picto URL.</value>
        public string PictoUrl { get; set; }
    }
}

MVC5i18n/Models/LocalizationModel.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace MVC5i18n.Models
{
    /// <summary>
    /// Classe définissant le modèle des choix de langues 
    /// </summary>
    public class LocalizationModel
    {

        IEnumerable<LanguageItemModel> languages;

        /// <summary>
        /// Gets or sets the languages items.
        /// </summary>
        /// <value>The items.</value>
        public IEnumerable<LanguageItemModel> Languages
        {
            get
            {
                return languages;
            }
            set { languages = value; }
        }

        /// <summary>
        /// Gets the lauguage items.
        /// </summary>
        /// <value>The lauguage items.</value>
        public SelectList LanguageItems
        {
            get
            {
                if (languages != null && languages.Any())
                    return new SelectList(languages, "Name", "DisplayName", SelectedLanguageCode);//languages.Select(l => new SelectListItem() { Selected = l.Equals(SelectedLanguage), Text = l.DisplayName, Value = l.Name });
                return null;
            }
        }

        /// <summary>
        /// Gets or sets the code of the selected language.
        /// </summary>
        /// <value>The code of the selected language.</value>
        public string SelectedLanguageCode { get; set; }


        /// <summary>
        /// Gets or sets the selected language.
        /// </summary>
        /// <value>The selected language.</value>
        public LanguageItemModel SelectedLanguage
        {
            get
            {
                if (!string.IsNullOrEmpty(SelectedLanguageCode) && Languages != null && Languages.Any())
                    return Languages.FirstOrDefault(l => l.Name == SelectedLanguageCode);
                else return null;
            }
        }
    }
}

MVC5i18n/Models/Person.cs
using System.ComponentModel.DataAnnotations;

namespace MVC5i18n.Models
{
    public class Person
    {
        [Display(Name = "FirstName", ResourceType = typeof(Resources.Resource))]
        [Required(ErrorMessageResourceType = typeof(Resources.Resource),
                  ErrorMessageResourceName = "FirstNameRequired")]
        [StringLength(50, ErrorMessageResourceType = typeof(Resources.Resource),
                          ErrorMessageResourceName = "FirstNameLong")]
        public string FirstName { get; set; }

        [Display(Name = "LastName", ResourceType = typeof(Resources.Resource))]
        [Required(ErrorMessageResourceType = typeof(Resources.Resource),
                  ErrorMessageResourceName = "LastNameRequired")]
        [StringLength(50, ErrorMessageResourceType = typeof(Resources.Resource),
                          ErrorMessageResourceName = "LastNameLong")]
        public string LastName { get; set; }


        [Display(Name = "Age", ResourceType = typeof(Resources.Resource))]
        [Required(ErrorMessageResourceType = typeof(Resources.Resource),
                  ErrorMessageResourceName = "AgeRequired")]
        [Range(0, 130, ErrorMessageResourceType = typeof(Resources.Resource),
                       ErrorMessageResourceName = "AgeRange")]
        public int Age { get; set; }


        [Display(Name = "Email", ResourceType = typeof(Resources.Resource))]
        [Required(ErrorMessageResourceType = typeof(Resources.Resource),
                  ErrorMessageResourceName = "EmailRequired")]
        [RegularExpression(".+@.+\\..+", ErrorMessageResourceType = typeof(Resources.Resource),
                                         ErrorMessageResourceName = "EmailInvalid")]
        public string Email { get; set; }


        [Display(Name = "Biography", ResourceType = typeof(Resources.Resource))]
        public string Biography { get; set; }
    }
}

MVC5i18n/Controllers/BaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using MVC5i18n.Helpers;
using MVC5i18n.Manager.Session;
using MVC5i18n.Models;

namespace MVC5i18n.Controllers
{
    public class BaseController : Controller
    {
        protected override IAsyncResult BeginExecuteCore(AsyncCallback callback, object state)
        {
            string cultureName = null;

            // Attempt to read the culture cookie from Request
            HttpCookie cultureCookie = Request.Cookies["_culture"];
            if (cultureCookie != null)
                cultureName = cultureCookie.Value;
            else
                cultureName = Request.UserLanguages != null && Request.UserLanguages.Length > 0 ?
                        Request.UserLanguages[0] :  // obtain it from HTTP header AcceptLanguages
                        null;
            // Validate culture name
            cultureName = CultureHelper.GetImplementedCulture(cultureName); // This is safe

            // Modify current thread's cultures            
            Thread.CurrentThread.CurrentCulture = new System.Globalization.CultureInfo(cultureName);
            Thread.CurrentThread.CurrentUICulture = Thread.CurrentThread.CurrentCulture;

            return base.BeginExecuteCore(callback, state);
        }

        [ChildActionOnly]
        [AllowAnonymous]
        public virtual ActionResult Localize()
        {
            return PartialView();
        }


        public ActionResult SetCulture(string culture)
        {
            // Validate input
            culture = CultureHelper.GetImplementedCulture(culture);

            // Save culture in a cookie
            HttpCookie cookie = Request.Cookies["_culture"];
            if (cookie != null)
                cookie.Value = culture;   // update cookie value
            else
            {

                cookie = new HttpCookie("_culture");
                cookie.Value = culture;
                cookie.Expires = DateTime.Now.AddYears(1);
            }
            Response.Cookies.Add(cookie);

            if (Request.UrlReferrer != null)
                return Redirect(Request.UrlReferrer.AbsolutePath + Request.UrlReferrer.Query);
            else
                return RedirectToAction("Index", "Home");
        }
    }

    
}

MVC5i18n/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC5i18n.Helpers;

namespace MVC5i18n.Controllers
{
    public class HomeController : BaseController
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        
    }
}

MVC5i18n/Views/Base/Localize.cshtml
@using MVC5i18n.Helpers
<script type="text/javascript">
</script>
@using (Html.BeginForm("SetCulture", "Base"))
{
    var culture = System.Threading.Thread.CurrentThread.CurrentUICulture.Name.ToLowerInvariant();
    @Html.Hidden("culture",culture)
    @Html.SelectMenu("language",culture , new {@class = "custom"});
}

MVC5i18n/Views/Home/About.cshtml
@model MVC5i18n.Models.Person

@{
    ViewBag.Title = Resources.AddPerson;
    var culture = System.Threading.Thread.CurrentThread.CurrentUICulture.Name.ToLowerInvariant();
}

@helper selected(string c, string culture)
{
if (c == culture)
{
        @:checked="checked"
    }
}

<h2>@Resources.AddPerson</h2>

@using (Html.BeginForm("SetCulture", "Home"))
{
    <fieldset>
        <legend>@Resources.ChooseYourLanguage</legend>

        <div class="control-group">
            <div class="controls">
                <label for="en-us">
                    <input name="culture" id="en-us" value="en-us" type="radio" @selected("en-us", culture) /> English
                </label>
            </div>
        </div>

        <div class="control-group">
            <div class="controls">
                <label for="es">
                    <input name="culture" id="es" value="es" type="radio" @selected("es", culture) /> Español
                </label>
            </div>
        </div>

        <div class="control-group">
            <div class="controls">
                <label for="ar">
                    <input name="culture" id="ar" value="ar" type="radio" @selected("ar", culture) /> العربية
                </label>
            </div>
        </div>


    </fieldset>




}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName)
                @Html.ValidationMessageFor(model => model.FirstName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName)
                @Html.ValidationMessageFor(model => model.LastName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Age, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Age)
                @Html.ValidationMessageFor(model => model.Age)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email)
                @Html.ValidationMessageFor(model => model.Email)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Biography, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Biography)
                @Html.ValidationMessageFor(model => model.Biography)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="@Resources." class="btn btn-default" />
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script type="text/javascript">
        (function ($) {
            $("input[type = 'radio']").click(function () {
                $(this).parents("form").submit(); // post form
            });

        })(jQuery);
    </script>
}

MVC5i18n/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MVC5i18n/Views/Home/Index.cshtml
@model MVC5i18n.Models.Person

@{
    ViewBag.Title = Resource.AddPerson;
    var culture = System.Threading.Thread.CurrentThread.CurrentUICulture.Name.ToLowerInvariant();
}


<h2>@Resource.AddPerson</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName)
                @Html.ValidationMessageFor(model => model.FirstName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName)
                @Html.ValidationMessageFor(model => model.LastName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Age, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Age)
                @Html.ValidationMessageFor(model => model.Age)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email)
                @Html.ValidationMessageFor(model => model.Email)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Biography, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Biography)
                @Html.ValidationMessageFor(model => model.Biography)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="@Resource.Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script type="text/javascript">
        (function ($) {
            $(".language").click(function () {
                $("#culture").val(this.text);
                $(this).parents("form").submit(); // post form
            });

        })(jQuery);
    </script>
}

MVC5i18n/Views/Shared/_Layout.cshtml
@using MVC5i18n.Helpers
<!DOCTYPE html>
<html lang="@CultureHelper.GetCurrentNeutralCulture()" dir="@(CultureHelper.IsRighToLeft() ? "rtl" : "ltr")">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css" + (CultureHelper.IsRighToLeft() ? "-rtl" : ""))
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })

                
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>
                        @{ Html.RenderAction("Localize", "Base");}
                    </li>
                    @*<li>
                        <div class="btn-group">
                            <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#">ES <span class="caret"></span></a>

                            <ul class="dropdown-menu">
                                <li>
                                    <a href="#">ES</a>

                                </li>
                                <li>
                                    <a href="#">FR</a>

                                </li>
                                <li>
                                    <a href="#">EN</a>

                                </li>
                            </ul>
                        </div>
                    </li>*@
                </ul>
            </div>
        </div>
    </div>
<div class="container body-content">
    @RenderBody()
    <hr/>
    <footer>
        <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
    </footer>
</div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap" + (CultureHelper.IsRighToLeft() ? "-rtl" : ""))
    @RenderSection("scripts", required: false)

    <script type="text/javascript">
        (function ($) {
            $(".language").click(function () {
                $("#culture").val(this.text);
                $(this).parents("form").submit(); // post form
            });

        })(jQuery);
    </script>
</body>
</html>